# Changes here will be overwritten by Copier
_commit: dd79d05
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: true
copyright_year: '2025'
documentation: true
email: mark@securehst.com
full_name: Mark Moreno
github_username: markm-io
has_cli: false
initial_commit: true
is_django_package: false
open_source_license: MIT
package_name: dataframe_to_pg
project_name: Dataframe to Postgres
project_short_description: DataFrame to PostgreSQL Writer
project_slug: dataframe-to-pg
run_uv_sync: true
setup_github: false
setup_pre_commit: true

