name: Sync Github labels

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"

jobs:
  labels:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install labels
        run: pip install labels
      - name: Check Labels version
        run: labels --version
      - name: Check Upgrade Labels
        run: pip install --upgrade labels
      - name: Check Labels version2
        run: labels --version
      - name: Sync config with Github
        run: labels -u ${{ github.repository_owner }} -t ${{ secrets.GH_PAT }} sync -f .github/labels.toml
